const rows = [
  {
    QRcode: 'fdhghgjghjghjh',
    ExpirationDate: '2022-02-02',
    KitType: 1,
    createdBy: 'admin',
    updatedBy: 'admin',
    id: 1,
  },
  {
    QRcode: 'fdhghgjghjghjh',
    ExpirationDate: '2022-02-02',
    KitType: 1,
    createdBy: 'admin',
    updatedBy: 'admin',
    id: 2,
  },
  {
    QRcode: 'fdhghgjghjghjh',
    ExpirationDate: '2022-02-02',
    KitType: 1,
    createdBy: 'admin',
    updatedBy: 'admin',
    id: 3,
  },
  {
    QRcode: 'fdhghgjghjghjh',
    ExpirationDate: '2022-02-02',
    KitType: 1,
    createdBy: 'admin',
    updatedBy: 'admin',
    id: 4,
  },
  {
    QRcode: 'fdhghgjghjghjh',
    ExpirationDate: '2022-02-02',
    KitType: 1,
    createdBy: 'admin',
    updatedBy: 'admin',
    id: 3,
  },
  {
    QRcode: 'fdhghgjghjghjh',
    ExpirationDate: '2022-02-02',
    KitType: 1,
    createdBy: 'admin',
    updatedBy: 'admin',
    id: 4,
  },
  {
    QRcode: 'fdhghgjghjghjh',
    ExpirationDate: '2022-02-02',
    KitType: 1,
    createdBy: 'admin',
    updatedBy: 'admin',
    id: 3,
  },
  {
    QRcode: 'fdhghgjghjghjh',
    ExpirationDate: '2022-02-02',
    KitType: 1,
    createdBy: 'admin',
    updatedBy: 'admin',
    id: 1,
  },
  {
    QRcode: 'fdhghgjghjghjh',
    ExpirationDate: '2022-02-02',
    KitType: 1,
    createdBy: 'admin',
    updatedBy: 'admin',
    id: 2,
  },
  {
    QRcode: 'fdhghgjghjghjh',
    ExpirationDate: '2022-02-02',
    KitType: 1,
    createdBy: 'admin',
    updatedBy: 'admin',
    id: 3,
  },
  {
    QRcode: 'fdhghgjghjghjh',
    ExpirationDate: '2022-02-02',
    KitType: 1,
    createdBy: 'admin',
    updatedBy: 'admin',
    id: 4,
  },
  {
    QRcode: 'fdhghgjghjghjh',
    ExpirationDate: '2022-02-02',
    KitType: 1,
    createdBy: 'admin',
    updatedBy: 'admin',
    id: 3,
  },
  {
    QRcode: 'fdhghgjghjghjh',
    ExpirationDate: '2022-02-02',
    KitType: 1,
    createdBy: 'admin',
    updatedBy: 'admin',
    id: 4,
  },
  {
    QRcode: 'fdhghgjghjghjh',
    ExpirationDate: '2022-02-02',
    KitType: 1,
    createdBy: 'admin',
    updatedBy: 'admin',
    id: 3,
  },
];

export default rows;
